name: New Pull Request

on: pull_request
jobs: 
  new-pull-request: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install dependencies, run lint and build
          run: yarn install --frozen-lockfile
          run: yarn lint
          run: yarn build