name: New Pull Request

on: pull_request
jobs: 
  new-pull-request: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: run install, lint, build and test
        run: | 
          npm install
          npm run build
          npm run test

    